# Generated by Django 6.0.7 on 2026-07-18 04:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, max_length=255, null=True)),
                ('tier', models.CharField(choices=[('new', 'New'), ('loyal', 'Loyal'), ('vip', 'VIP')], default='new', max_length=20, verbose_name='Customer Tier')),
                ('total_orders', models.IntegerField(default=0, verbose_name='Total Orders')),
                ('total_spent', models.PositiveBigIntegerField(default=0, verbose_name='Total Spent')),
                ('joined_at', models.DateField(default=datetime.date.today, verbose_name='Joined Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
