# Generated by Django 6.0.7 on 2026-07-25 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymovement',
            name='movement_type',
            field=models.CharField(choices=[('sale', 'Sale'), ('purchase', 'Purchase'), ('return', 'Return'), ('adjustment', 'Adjustment'), ('supplier_return', 'Supplier Return')], max_length=20),
        ),
    ]
