# Generated by Django 6.0.7 on 2026-07-18 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=60, unique=True)),
                ('variant_name', models.CharField(blank=True, max_length=120, null=True)),
                ('size', models.CharField(blank=True, max_length=40, null=True)),
                ('color', models.CharField(blank=True, max_length=40, null=True)),
                ('price', models.PositiveBigIntegerField()),
                ('cost_price', models.PositiveBigIntegerField(blank=True, null=True)),
                ('stock', models.IntegerField(default=0)),
                ('low_stock_threshold', models.IntegerField(default=5)),
                ('variant_status', models.CharField(choices=[('active', 'Active'), ('low', 'Low'), ('out', 'Out'), ('hidden', 'Hidden')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product')),
            ],
        ),
    ]
