# Generated by Django 6.0.7 on 2026-09-19 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_emoji_remove_product_tint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(default='Cái', max_length=20),
        ),
    ]
