# Generated by Django 6.0.7 on 2026-09-19 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'COD'), ('transfer', 'Transfer'), ('cash', 'Cash')], default='cash', max_length=20),
        ),
    ]
