# Generated by Django 6.0.7 on 2026-07-24 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0003_remove_product_emoji_remove_product_tint_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('refund_amount', models.PositiveBigIntegerField(default=0)),
                ('refund_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('transfer', 'Transfer'), ('card', 'Card'), ('momo', 'Momo')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='orders.order')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns', to='users.user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('unit_price', models.PositiveBigIntegerField()),
                ('line_total', models.PositiveBigIntegerField()),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_items', to='orders.orderitem')),
                ('return_slip', models.ForeignKey(db_column='return_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='returns.return')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_items', to='products.productvariant')),
            ],
        ),
    ]
